name: ArmorStandArms
version: 1.0
main: me.markiscool.armorstandarms.ArmorStandArmsPlugin
api-version: 1.13
author: MarkIsCool
description: Shift click to place armor stands with arms. Permission is armorstandarms.allow